#!/bin/bash -x
# Create a USB stick to double boot in 32bit and 64bit tiny core linux
# For the purpose of duplicating rpi SD cards on a windows laptop

#Copyright George Hunt @ georgejhunt@gmail.com
# attributioon James Camron http://dev.laptop.org/git/users/quozl/mktinycorexo/

if [ $(id -u) = "0" ]; then
   echo This script should be run as user tc
   exit 1
fi
tce-load -wi dosfstools e2fsprogs

efi=sdc2
ext=sdc3
sudo umount /mnt/$efi
sudo umount /mnt/$ext

sudo fdisk /dev/sdc << EOF
d

d

d

n
p
1
2048
+1M
n
p
2

+200M
n
p
3

+1G
t
1
4
t
2
1
t
3
20
w
EOF

sleep 5
sudo partprobe /dev/sdc

sudo mke2fs -t ext2 -L tcore  -F /dev/$ext
sudo mkfs.vfat /dev/$efi

uuid=$(blkid /dev/$ext | cut -d'"' -f4)
echo $uuid

tce-load -i grub2-multi
sudo mount /dev/$efi /mnt/$efi
sudo mount /dev/$ext /mnt/$ext

sudo grub-install -s --target=x86_64-efi --boot-directory=/mnt/$efi/EFI/BOOT --efi-directory=/mnt/$efi --removable --directory=/usr/local/lib/grub/i386-efi/
if [ $? -ne 0 ];then exit 1;fi
sudo grub-install --target=i386-pc --boot-directory=/mnt/$efi/EFI/BOOT /dev/sdc
if [ $? -ne 0 ];then exit 1;fi

cat grub.cfg | sed -e "s/IIAB_TOKEN/$uuid/g" | sudo tee /mnt/$efi/EFI/BOOT/grub/grub.cfg

sudo mkdir -p /mnt/$ext/boot
sudo mkdir -p /mnt/$ext/tce/optional
sudo mkdir -p /mnt/$ext/opt/iiab
sudo mkdir -p /mnt/$ext/home

pushd /mnt/$ext/boot
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/vmlinuz
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/vmlinuz64
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/rootfs.gz
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/modules.gz
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/modules64.gz
popd

sudo cp iiab.lst /mnt/$ext/tce/

sudo cp /mnt/sdb2/tce/mydata.tgz /mnt/$ext/tce/mydata.tgz
sudo cp -r /mnt/sdb2/opt /mnt/$ext/
sudo cp -f load.sh /mnt/$ext/tce
if [ ! -d /mnt/$ext/opt/iiab/iiab-factory ]; then
   pushd /mnt/$ext/opt/iiab
      sudo git clone https://github.com/iiab/iiab-factory
   popd
fi
