- name: Install video and audio packages
  package:
    name:
      - pulseaudio
      - simplescreenrecorder
      - youtube-dl
      - openshot
      - pavucontrol
      - ffmpeg
      - cheese
      - vim-gtk3
    state: present
  tags:
    - download

- name: Create directories for videos
  file:
     path: "{{ item }}"
     state: directory
  with_items:
      - "{{ doc_root }}/info/video"
      - "{{ doc_root }}/video"
     
- name: Copy the files needed
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: "viewer.php", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "viewer.css", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "viewer.js", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "video-js.css", dest: "{{ doc_root }}/info/videos/"  }

- name: Enable the videos config for apache
  file:
      src: /etc/apache2/sites-available/production.conf
      dest: /etc/apache2/sites-enabled/production.conf
      state: link

- name: Get saved video.js which displays closed captions
  get_url:
      url: '{{ iiab_download_url }}/../content/videos/video.js'
      dest: '{{ doc_root }}/info/videos/'

- name: Get tool for downloading youtube closed captions
  get_url:
      url: '{{ iiab_download_url }}/../content/videos/save-vtt-files.js'
      dest: '{{ doc_root }}/info/videos/'
