- name: Install video and audio packages
  package:
    name:
      - pulseaudio
      - simplescreenrecorder
      - youtube-dl
      - openshot
      - pavucontrol
      - gimp
      - ffmpeg
      - cheese
      - vim-gtk3
      - python-flask
      - php-getid3
      - gnome-screenshot
    state: present
  tags:
    - download

- name: Add required directories
  file:
      path: '{{ item }}'
      state: directory
  with_items:
      - '{{ production_dir }}/webpack'
      - '{{ production_dir }}/static'
      - '{{ production_dir }}/templates'

- name: Copy the files needed
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
  with_items:
      - { src: "viewer.php", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "viewer.css", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "viewer.js", dest: "{{ doc_root }}/info/videos/"  }
      - { src: "video-js.css", dest: "{{ doc_root }}/info/videos/"  }

- name: Install flask with dependencies using pip, into virtualenv
  pip:
    name: 
      - flask 
      - googletrans
    virtualenv: "{{ production_venv }}"
    virtualenv_python: python3
  when: internet_available | bool

- name: Configure Apache to serve wsgi python server for videos metadata update
  template:
      dest: /etc/apache2/sites-available/production.conf
      src: production.conf.apache

- name: Enable the videos config for apache
  file:
      src: /etc/apache2/sites-available/production.conf
      dest: /etc/apache2/sites-enabled/production.conf
      state: link

- name: Get saved video.js which displays closed captions
  get_url:
      url: '{{ iiab_download_url }}/../content/videos/video.js'
      dest: '{{ doc_root }}/info/videos/'
  when: internet_available | bool
